-- Enable the pgvector extension to work with embedding vectors
create extension if not exists vector;

-- 1. PROFILES TABLE (Replaces core_memory.json)
create table profiles (
  user_id text primary key,
  persona_config text,       -- Stores the base system prompt/persona
  user_profile jsonb,        -- Stores the psychological profile (Meta-Cognition)
  relationship_state jsonb,  -- Stores UserRelationship object
  emotional_state jsonb,     -- Stores EmotionalState object
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. MEMORIES TABLE (Replaces ChromaDB)
create table memories (
  id uuid primary key default gen_random_uuid(),
  user_id text references profiles(user_id),
  content text not null,
  embedding vector(384),     -- Compatible with all-MiniLM-L6-v2
  metadata jsonb,            -- Stores tags, importance, timestamp
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. CHAT LOGS TABLE (New raw history)
create table chat_logs (
  id bigint generated by default as identity primary key,
  user_id text references profiles(user_id),
  role text not null,        -- 'user' or 'assistant'
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. VECTOR SEARCH FUNCTION (RPC)
create or replace function match_memories (
  query_embedding vector(384),
  match_threshold float,
  match_count int,
  filter_user_id text
)
returns table (
  id uuid,
  content text,
  metadata jsonb,
  similarity float
)
language plpgsql
as $$
begin
  return query;
  select
    memories.id,
    memories.content,
    memories.metadata,
    1 - (memories.embedding <=> query_embedding) as similarity
  from memories
  where 1 - (memories.embedding <=> query_embedding) > match_threshold
  and memories.user_id = filter_user_id
  order by memories.embedding <=> query_embedding
  limit match_count;
end;
$$;
