-- Enable the pgvector extension to work with embedding vectors
create extension if not exists vector;

-- 1. PROFILES TABLE (Replaces core_memory.json)
create table profiles (
  user_id text primary key,
  persona_config text,       -- Stores the base system prompt/persona
  user_profile jsonb,        -- Stores the psychological profile (Meta-Cognition)
  relationship_state jsonb,  -- Stores UserRelationship object
  emotional_state jsonb,     -- Stores EmotionalState object
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. MEMORIES TABLE (Replaces ChromaDB)
create table memories (
  id uuid primary key default gen_random_uuid(),
  user_id text references profiles(user_id),
  content text not null,
  embedding vector(384),     -- Compatible with all-MiniLM-L6-v2
  metadata jsonb,            -- Stores tags, importance, timestamp
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. CHAT LOGS TABLE (New raw history)
create table chat_logs (
  id bigint generated by default as identity primary key,
  user_id text not null references profiles(user_id),
  role text not null,        -- 'user' or 'assistant'
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  constraint chat_logs_user_id_id_key unique (user_id, id)
);

-- 4. VECTOR SEARCH FUNCTION (RPC)
create or replace function match_memories (
  query_embedding vector(384),
  match_threshold float,
  match_count int,
  filter_user_id text
)
returns table (
  id uuid,
  content text,
  metadata jsonb,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    memories.id,
    memories.content,
    memories.metadata,
    1 - (memories.embedding <=> query_embedding) as similarity
  from memories
  where 1 - (memories.embedding <=> query_embedding) > match_threshold
  and memories.user_id = filter_user_id
  order by memories.embedding <=> query_embedding
  limit match_count;
end;
$$;

-- 5. ARCHIVAL EXTRACTIONS TABLE
create table if not exists archival_extractions (
  user_id text not null references profiles(user_id) on delete cascade,
  source_chat_log_id bigint not null,
  extractor_version integer not null,
  schema_version integer not null,
  idempotency_key text not null,
  facts jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  primary key (user_id, source_chat_log_id, extractor_version),
  foreign key (user_id, source_chat_log_id) references chat_logs(user_id, id) on delete cascade,
  constraint archival_extractions_idempotency_key_idx unique (idempotency_key)
);

create index if not exists archival_extractions_user_id_idx on archival_extractions(user_id);

alter table archival_extractions enable row level security;

create policy "Users can select their own archival extractions"
  on archival_extractions
  for select
  using (auth.uid()::text = user_id);
